# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages

r_github_packages:
  - davidgohel/officedown
  - overdodactyl/mayotheme
  - jimhester/lintr

before_install:
 - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

before_cache:
 - Rscript -e 'install.packages("pkgdown")'
 - Rscript -e 'remotes::install_github("mayoverse/mayotemplate")'
deploy:
  provider: script
  script: Rscript -e 'install.packages("pkgdown"); pkgdown::deploy_site_github()'
  skip_cleanup: true
